version: 2

sources:
  - name: pipedrive
    database: postgres
    schema: public  
    tables:
      - name: deal_changes
      - name: stages
      - name: activity
      - name: activity_types
      - name: users
      - name: fields
